function tolerance = getLaplaceCmapModelVoltChargeTolerance(model)
%GETLAPLACECMAPMODELVOLTCHARGETOLERANCE Read the shared auxiliary tolerance.

has_new = isfield(model,'volt_charge_action_tolerance') && ...
    ~isempty(model.volt_charge_action_tolerance);
has_legacy = isfield(model,'charge_action_tolerance') && ...
    ~isempty(model.charge_action_tolerance);
if has_new && has_legacy && ...
        ~isequaln(model.volt_charge_action_tolerance, ...
        model.charge_action_tolerance)
    error('getLaplaceCmapModelVoltChargeTolerance:ConflictingTolerance', ...
        ['The model contains different volt_charge_action_tolerance and ', ...
         'legacy charge_action_tolerance values.']);
elseif has_new
    tolerance = model.volt_charge_action_tolerance;
elseif has_legacy
    tolerance = model.charge_action_tolerance;
else
    error('getLaplaceCmapModelVoltChargeTolerance:MissingTolerance', ...
        'The model does not contain a voltage/charge action tolerance.');
end
end
