function signature = normalizeLaplaceCmapInterpolationSignature( ...
        signature,problem)
%NORMALIZELAPLACECMAPINTERPOLATIONSIGNATURE Normalize legacy model fields.

problem = resolveLaplaceInterpolationProblem(problem,mfilename);
if ~isstruct(signature) || ~isscalar(signature)
    error('normalizeLaplaceCmapInterpolationSignature:BadSignature', ...
        'The interpolation signature must be a scalar struct.');
end

has_new = isfield(signature,'volt_charge_interp_tol') && ...
    ~isempty(signature.volt_charge_interp_tol);
has_legacy = isfield(signature,'charge_interpolation_tol') && ...
    ~isempty(signature.charge_interpolation_tol);
if has_new && has_legacy && ...
        ~isequaln(signature.volt_charge_interp_tol, ...
        signature.charge_interpolation_tol)
    error('normalizeLaplaceCmapInterpolationSignature:ConflictingTolerance', ...
        ['The signature contains different volt_charge_interp_tol and ', ...
         'legacy charge_interpolation_tol values.']);
elseif ~has_new && has_legacy
    signature.volt_charge_interp_tol = ...
        signature.charge_interpolation_tol;
end
if isfield(signature,'charge_interpolation_tol')
    signature = rmfield(signature,'charge_interpolation_tol');
end
if isfield(signature,'problem') && ~isempty(signature.problem) && ...
        ~strcmp(resolveLaplaceInterpolationProblem(signature.problem,mfilename), ...
        problem)
    error('normalizeLaplaceCmapInterpolationSignature:WrongProblem', ...
        'The signature belongs to a different Laplace problem.');
end
expected_projection = strcmp(problem,'elastance');
if isfield(signature,'project_charge') && ...
        ~isempty(signature.project_charge) && ...
        (~isscalar(signature.project_charge) || ...
        logical(signature.project_charge) ~= expected_projection)
    error('normalizeLaplaceCmapInterpolationSignature:WrongProjection', ...
        'The signature charge-projection setting conflicts with its problem.');
end
signature.problem = problem;
signature.project_charge = strcmp(problem,'elastance');
signature = orderfields(signature);
end
